
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS INVITATION;


CREATE TABLE MEMBER
(
  MEMBER_ID varchar(100) PRIMARY Key not null ,
  MEMBER_NAME varchar(100) not null ,
  MEMBER_PHONE varchar(20) not null ,
  MEMBER_EMAIL varchar (100) not null ,
  MEMBER_STATUS varchar (20),
  CREATED_DATE TIMESTAMP,
  UDATED_DATE TIMESTAMP

);

CREATE TABLE INVITATION (
  INVITATION_ID INT  PRIMARY KEY NOT NULL,
  INVITE_CODE VARCHAR(50),
  INVITE_CODE_STATUS VARCHAR(20),
  CREATED_DATE TIMESTAMP,
  UPDATED_DATE TIMESTAMP,
  EXPIRE_DATE TIMESTAMP
);




